Clean up code of FlinkOperation
apache/incubator-kyuubi pull request #1756
Opened 2022-01-13 09:56 UTC by pan3793

### _Why are the changes needed?_

Minor code cleanup.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/develop_tools/testing.html#running-tests) locally before make a pull request

2022-01-14 02:46 UTC, yanghua approved these changes
LGTM

2022-01-14 02:46 UTC, yanghua commented on externals/kyuubi-flink-sql-engine/src/main/scala/org/apache/kyuubi/engine/flink/operation/GetTables.scala
> +            flinkCatalog.listTables(_schema).asScala
In flink, it uses `database` to represent `schema`, e.g. `listTables(database)`. But, on the other side, it's ok to follow general understood. I am ok.

2022-01-14 05:42 UTC, SteNicholas requested changes

2022-01-14 05:42 UTC, SteNicholas commented on externals/kyuubi-flink-sql-engine/src/main/scala/org/apache/kyuubi/engine/flink/operation/GetTables.scala
> +          .filter { case schemaPattern(_*) => true; case _ => false }
This could use the `StringUtils.fliterPattern` in #1749 .

2022-01-16 10:15 UTC, pan3793 commented
Thanks, merging to master.

2022-01-16 10:15 UTC, closed without merging